spring:
  redis:
    password: 123456
    host: 192.168.109.135
    port: 6379
  datasource:
    username: mall_sms
    password: mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.109.135:3306/mall_sms
  application:
    name: mall-coupon

server:
  port: 7777

mybatis-plus:
  type-aliases-package: com.jxkj.usercenter
  mapper-locations: classpath*:mybatis/mapper/*.xml
  # mybatis-plus 的全局配置
  global-config:
    banner: false
  # mybatis 原生配置
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false