spring:
  cache:
    ehcache:
      config: ehcache.xml
  redis:
    database: 0
    host: 192.168.109.128
    port: 6379
    password: 123@456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
